version: "3.7"
services:
  jenkins:
    image: "jenkins/jenkins:2.319.1-lts"
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /home/thermo/WorkDir/VerProj/jenkins_home:/var/jenkins_home/
