# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
# Copyright 2021 Variscite Ltd.


FROM cic-ics-docker
USER root

MAINTAINER Nate Drude "roger.gu@thermofisher.com"

WORKDIR ~/
#TODO download meta-ics
RUN git clone git@github.com:thermofisher/cic-imx6_mpu-base.git

WORKDIR /workdir

#TODO soft-link meta-ics
RUN mkdir meta-vertumnus \
     && ln -s  ~/meta-vertumnus meta-vertumnus

RUN MACHINE=var-som-mx6 DISTRO=fslc-x11 . setup-environment build_jenkins

#revise local.conf, bblayer.conf; use COPY

COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]

USER jenkins
