# Copyright 2021 thermofisher.

FROM ubuntu:16.04
MAINTAINER  Roger gu "roger.gu@thermofisher.com"

RUN apt-get update
RUN apt-get install -y sudo openssl apt-utils

WORKDIR /workdir

# Define username and temporary uid and gid
ENV USER=ics USER_ID=1000 USER_GID=1000

# now creating user, change password to 'Therm0Fisher'
RUN groupadd --gid "${USER_GID}" "${USER}" && \
    useradd \
      --uid ${USER_ID} \
      --gid ${USER_GID} \
      --create-home \
      --shell /bin/bash\
      --password $(openssl passwd -1 Therm0Fisher)\
      ${USER}

#setup locale
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y locales && dpkg-reconfigure locales --frontend noninteractive && locale-gen "en_US.UTF-8" && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Yocto
RUN apt-get update && apt-get install -y \
     gawk wget git diffstat unzip texinfo gcc-multilib \
     build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
     xz-utils debianutils iputils-ping libsdl1.2-dev xterm \
     autoconf libtool libglib2.0-dev libarchive-dev \
     sed cvs subversion coreutils texi2html docbook-utils python-pysqlite2 \
     help2man make gcc g++ desktop-file-utils libgl1-mesa-dev libglu1-mesa-dev \
     mercurial automake groff curl lzop asciidoc u-boot-tools dos2unix mtd-utils pv \
     libncurses5 libncurses5-dev libncursesw5-dev libelf-dev zlib1g-dev bc rename \
     iproute2

RUN curl https://storage.googleapis.com/git-repo-downloads/repo > /bin/repo && chmod a+rx /bin/repo

# Install python3.6 for repo command
RUN apt-get install -y \
     build-essential checkinstall libreadline-gplv2-dev libncursesw5-dev libssl-dev \
     libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev && \
     wget https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tar.xz && \
     tar xvf Python-3.6.9.tar.xz && \
     cd Python-3.6.9/ && \
     ./configure && \
     sudo make altinstall -j 16

# Update to latest
RUN apt-get update && apt-get dist-upgrade -y

RUN repo init -u https://github.com/roger-gu-tfs/ics-bsp-platform.git -b vertumnus_0.9.0 -m default.xml \
     && repo sync

RUN MACHINE=var-som-mx6 DISTRO=fslc-x11 . setup-environment build_jenkins

#TODO: revise local.conf, bblayer.conf; use COPY or ECHO

COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]
